name: flutter_quiz_app
description: Une application de quiz interactive avec différents thèmes.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.5
  shared_preferences: ^2.2.0
  google_fonts: ^6.1.0
  animated_text_kit: ^4.2.2
  lottie: ^2.7.0
  flutter_animate: ^4.3.0
  confetti: ^0.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/animations/
    - assets/images/ 